### ISSUE TITLE
Would you be interested in merging this into mainline?

### ISSUE THREAD

**Issue by Starz0r** [Curve/areweanticheat#1]
Happened to stumble upon this repository, and I have to say, great work! This looks way better than my site in multiple different ways. I'm wondering if you'd be interested in allowing this frontend to be used instead of mine. If so, I really only had a few small gripes:

1. This repository does not have any license, so it would be hard to get contributions back without one.
2. I built my original frontend with being able to run entirely without JavaScript. However, a lot of the good improvements this site makes does not seem to work without JavaScript. I'm wondering if it's even worth it to try to do that because a lot of informational Linux sites like [ProtonDB](https://protondb.com) do not seem to adhere to this principal anyway.

I'm interested in hearing back and seeing what you think about this, thanks!

**Comment by Curve** [comment]
Hey, thanks for the interest!

I'd be happy to merge this into mainline, 

1. I'd like to follow MIT, I'll add a license as soon as I'm back on PC
2. I think with some work the code can be statically generated (except for the changes list)

**Comment by Curve** [comment]
I added a license and refactored most of the code, as for the no javascript part, I could move the project to nextjs, that should allow static site generation and should at least allow the website to run and show the games and their status.

However the Changes List and Search will most likely break without JS.

**Comment by Starz0r** [comment]
It may not be worth designing a site that doesn't function without JavaScript. In reality, most users will likely have some subset of capabilities enabled.

Sometime this week, I'll try adding a codeowners file to the main repository to allow you to have your own branch until it gets merged.

**Comment by Curve** [comment]
Sounds good!

**Comment by Curve** [comment]
> It may not be worth designing a site that doesn't function without JavaScript. In reality, most users will likely have some subset of capabilities enabled.
> 
> Sometime this week, I'll try adding a codeowners file to the main repository to allow you to have your own branch until it gets merged.

Hey, hope I don't bother but have you made any progress on this?  
I've addressed a few issues from mainline here, I'll maybe take a look at some more later ^^

If you want we could try to make a new branch in mainline that tries to gracefully move the mainline codebase to be compatible with this fork :)

**Comment by Starz0r** [comment]
@Curve Apologies! I had absolutely forgotten about this because of how busy I had gotten afterwards.

I've sent the invite to the repository, you should be able to push any changes you'd like to the `redesign` branch! Let me know if there are any further issues or problems you'd like me to help you with :)

**Comment by Curve** [comment]
> @Curve Apologies! I had absolutely forgotten about this because of how busy I had gotten afterwards.
> 
> I've sent the invite to the repository, you should be able to push any changes you'd like to the `redesign` branch! Let me know if there are any further issues or problems you'd like me to help you with :)

Thanks! I'll try to get to adjusting the source this evening :D

**Comment by Curve** [comment]
@Starz0r I'm currently rewriting the Website with next and made the page accessible without JavaScript, I've already pushed this to the redesign branch

Also, may I contact you outside of GitHub?

**Comment by Starz0r** [comment]
Sure, you can contact me on Discord.
